import type { Metadata } from "next";
import "./globals.css";
import { CivicAuthProvider } from "@civic/auth-web3/nextjs";
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // choose weights you need
  variable: '--font-poppins', // optional, for Tailwind use
});
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
    <html lang="en">
      <body
        className={poppins.variable}
      >
        <CivicAuthProvider>
        {children}
        </CivicAuthProvider>
      </body>
    </html>
    
  );
}
